### PR TITLE
Update Script: Syncthing.sh Fix wrong config path

### LINKED ISSUE #752: Syncthing.sh wrong config path
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

During the install der is a call to a wrong/older config path:

'[ERROR] in line 31: exit code 0: while executing command sed -i "{s/127.0.0.1:8384/0.0.0.0:8384/g}" /root/.local/state/syncthing/config.xml`

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

_No response_

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Fixes a the wrong config path during installation.
Fixes #752

## Type of change
Please check the relevant option(s):

- [X] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [X] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [X] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Comment by havardthom** [comment]
According to this https://docs.syncthing.net/users/config.html#description `$HOME/.local/state/syncthing` its the correct location after `v1.27.0`, it was `$HOME/.config/syncthing` before that?

**Comment by michelroegl-brunner** [comment]
Yes i‘ve seen that in the docs. But if you install it with Default Settings under Debian 12 ther is no file created under `$HOME/.local/state/syncthing `, the script fails on that sed command. After looking around in the LXC i found the config file under `$HOME/.config/syncthing `, therefore the propsed change. The exact version wich gets installed i have to check, but it get installed as a debian package via apt. so my guess is the latest version wich is [v1.28.1](https://github.com/syncthing/syncthing/releases/tag/v1.28.1). But i can invastigate more tomorrow.

**Comment by MickLesk** [comment]
Check If File exists, do sed, else sed other File?

**Comment by michelroegl-brunner** [comment]
Yeah great idea, i do this tommorw

**Comment by michelroegl-brunner** [comment]
Is changed as requested!

**Review by MickLesk — APPROVED** [review]

**Comment by havardthom** [comment]
This is an install script, why handle two config files?
I just installed Syncthing and had no errors. Version `v1.28.1` is installed and config is in `/root/.local/state/syncthing/config.xml`. I don't see any issue with the current script?

**Comment by michelroegl-brunner** [comment]
Wich repo did you install it from, i allways get this error. `bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/syncthing.sh)"`
syncthing

**Comment by havardthom** [comment]
```
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/syncthing.sh)"
```
image

**Comment by michelroegl-brunner** [comment]
It seems to be working for @MickLesk as well. Might be an isolated issue? Altough i cant understand why this would be.

**Pull request closed without merging**
