### PR TITLE
Remove Scrypted script

### LINKED ISSUE #494: Scrypted
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Hi, I’m the maintainer of Scrypted. I would appreciate it if Scrypted was removed from the helper scripts. It does not handle gpu/hardware pass-through correctly, and it has become a persistent support issue on my repository and discord. So much so, that I have added detection code to see if it’s from the helper script, and warn the user to install using the official script. There are official installation instructions and scripts for running Scrypted in proxmox already. 

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

_No response_

### PR DESCRIPTION
**Pull request by MickLesk**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description
Remove Scrypted from webpage for now

Fixes #494 

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [ ] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Comment by havardthom** [comment]
Let's just remove the whole script? Scrypted have their own install script https://github.com/koush/scrypted/blob/main/install/proxmox/install-scrypted-proxmox.sh

No need for a script here aswell imo

**Comment by MickLesk** [comment]
Can we do, but the Script is them broken :D

**Comment by havardthom** [comment]
Yes it's a breaking change, we can refer users to use the script maintained by Scrypted in CHANGELOG.md

**Review by havardthom — APPROVED** [review]

**Comment by judeibe** [comment]
Koush’s script does not work…

**Comment by MickLesk** [comment]
He was not interested in any solution. I'm not chasing after him. He just wanted it deleted. 

By the way: I could hardly find any problems with the script, no examples were provided, but that's just the way it is

**Pull request merged**
