### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Add CODEOWNERS so org teams get automatically assigned to PR requests. The org **teams** needs to have write access. Can only test after merge, so it might need some adjustments

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)
- [ ] Documentation update required (this change requires an update to the documentation)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Testing performed (I have tested my changes, ensuring everything works as expected)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Review by MickLesk — APPROVED** [review]

**Review by MickLesk — APPROVED** [review]

**Comment by MickLesk** [comment]
I cant merge. We need 2 Reviews?

**Comment by havardthom** [comment]
@MickLesk i think you need to add write access to `Frontend-Dev` team in the org

**Review by MickLesk — APPROVED** [review]

**Comment by havardthom** [comment]
> Frontend-dev already have write access (for the Repository - or needed for complete org?)

Works now, thanks

**Review by MickLesk — APPROVED** [review]

**Comment by havardthom** [comment]
@MickLesk please stop reapproving :sweat_smile: i need approval from another contributor

**Comment by MickLesk** [comment]
> @MickLesk please stop reapproving 😅 i need approval from another contributor

ah lol, the app fucked up and say, i need to do this :D confusing

**Review by Mellowlynx — APPROVED** [review]

**Pull request merged**
