### PR TITLE
Update to introduction on website

### LINKED ISSUE #210: improve clarity of script naming
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

i came to the site from hn, understanding that the site is about automating tasks on proxmox.
One of the first scripts I saw was the docker lxc script. The description of the script explains what docket is, which let me wonder if this is about running docker somehow nativley on proxmox. This is probably my fault by not reading the site properly, but I have two suggestions in mind:

Make Lxc stand out as a label that imakes clear its not part of the script title.

Make somehow clear that the script installs e.g. docker, because the only thing that is shown is a description of what docker is.

### Please provide a description of the expected behavior.

As written above.

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

_No response_

### PR DESCRIPTION
**Pull request by Mellowlynx**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Provide a summary of the changes made and/or reference the issue being addressed.

Fixes #210 
It adds a bit more info for those who did not see the GitHub jet.

## Type of change
Please check the relevant option(s):

- [x] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Review by MickLesk — APPROVED** [review]

**Review by havardthom — APPROVED** [review]

**Comment by BramSuurdje** [comment]
not a fan of this, maybe we can put it somewhere else? the header needs to be something clean and tidy, not this chunk of text that gets thrown in your face as soon as you enter

**Comment by MickLesk** [comment]
Basically, I don't care. The other @community-scripts/contributor are welcome to say something about it.

**Comment by Mellowlynx** [comment]
In my defence; If you visit the site now, and don't know the project at all, it's not clear what we offer.
Also not after going to the scripts.
image

It's adding just two sensises in 3 lines. (done this way so everything should be about the same width), and let a new commer know, what they are about to see.
I do agree to keep it clean, but this page does nothing right now, it just adds a anoying click here to get to the real stuff step.
Hands I use a /scripts bookmark.

**Comment by havardthom** [comment]
Can we see how the new landing page would look? I must admit I have also thought the extra button click is annoying compared to tteck's original page where you get directly to the scripts.

**Comment by BramSuurdje** [comment]
The idea for this homepage was to, in the future, add more information about what this project is and how to use it. It would also explain the steps the scripts take to complete an installation, since people have mentioned that it just looks like scripts are being piped into the terminal without explaining what each one does. I just haven’t had the time. Maybe that’s something @havardthom could work on. or i could but it would take a little longer

**Comment by Mellowlynx** [comment]
That sounds good, and there are higher priorities now I think, so meanwhile this is better than nothing, and it allows you plenty of time to enhance it at your own pace.

**Comment by BramSuurdje** [comment]
merging for now, will revert back to the old homepage in the future when better homepage has been made.

**Pull request merged**
