### PR TITLE
Fix Z-Wave JS UI script

### LINKED ISSUE #207: Zwave JS UI updated it's requirements to include ENV variables.
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

ZWave JS upgraded to version 14 of the node-zwave-js.   When doing so, they changed the requirements and now require enviornment variables to be set and don't default.   This change occured today with the update to tag 9.21.1.   With the variables 

The variables that must be set are ZWAVEJS_EXTERNAL_CONFIG and STORE_DIR.    If those are not configured, all the devices lose their manufacturer, product, and product code in the UI.  image

If you update the service entry being created in https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/zwave-js-ui.sh to include the variables - everything works as expected. 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Old
```
[Unit]
  Description=zwave-js-ui
  Wants=network-online.target
  After=network-online.target
  [Service]
  User=root
  WorkingDirectory=/opt/zwave-js-ui
  ExecStart=/opt/zwave-js-ui/zwave-js-ui-linux
  [Install]
  WantedBy=multi-user.target
```
New
```
[Unit]
  Description=zwave-js-ui
  Wants=network-online.target
  After=network-online.target
  [Service]
  Environment="ZWAVEJS_EXTERNAL_CONFIG=/opt/zwave-js-ui/.config-db"
  Environment="STORE_DIR=/opt/zwave-js-ui/store"
  User=root
  WorkingDirectory=/opt/zwave-js-ui
  ExecStart=/opt/zwave-js-ui/zwave-js-ui-linux
  [Install]
  WantedBy=multi-user.target
  ```

### Please provide detailed steps to reproduce the issue.

Update ZWAVE JS UI using the update script to version 9.21.0 or higher.

### PR DESCRIPTION
**Pull request by MickLesk**
## Description
An update was probably possible before, but it was programmed really badly.
I quickly reworked the whole script again. 

- Now it works with an .env file
- Not all user data is overwritten during the update
- Update adapted to our conventions

Fixes #207 

## Type of change
Please check the relevant option(s):

- [x] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Tested by User, migrated in Script.

### CODE REVIEW

**Review by havardthom — APPROVED** [review]

**Comment by schonzen** [comment]
I just finally found this breaking change that wasn't labeled as such after stumbling into the break while trying to troubleshoot a failing firmware upgrade. All I wanted was the new ZWave-JS, I didn't realize I was getting such a heavily reworked update script designed for an install script that didn't exist until this change. I'm new to this community, but really liked tteck's work.

Wouldn't it have made sense to need to write an update script that migrated to the new env method? Otherwise this is a purely breaking change for any install that existed before it.

I thought about writing an issue first but I wanted to find what happened where and found this.

**Comment by MickLesk** [comment]
1 second search in discussions:
https://github.com/community-scripts/ProxmoxVE/discussions/635

**Comment by havardthom** [comment]
I agree that this commit should be marked as breaking change, I will manually fix it in the changelog. Regarding update scripts handling breaking changes that applications choose to make, that is not in our scope and will make the scripts unmanageable over time.

**Comment by schonzen** [comment]
Oh, the break was from the script not the application.

**Pull request merged**
