### PR TITLE
Fix: install mosquitto from mosquitto repo

### PR DESCRIPTION
**Pull request by dsiebel**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

The `mosquitto` version from the official debian repositories is still [`2.0.11`, which was released in 2021, according to their git repository](https://github.com/eclipse-mosquitto/mosquitto/releases/tag/v2.0.11).
Running the `update` script would only ever update other packages, but never `mosquitto`.

This PR changes the install script to use the debian repository provided by Eclipse / Mosquitto, to get more recent versions.

This change will only affect new installs. Existing containers will continue to happily (not) update to any newer `mosquitto` version.

## Type of change

Please check the relevant option(s):

- [x] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites

The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

### CODE REVIEW

**Comment by MickLesk** [comment]
image

I can't reproduce this. For me (Debian 12) it is always up to date. I have been using the script for 2 years.

**Comment by dsiebel** [comment]
> I can't reproduce this. For me (Debian 12) it is always up to date. I have been using the script for 2 years.

That is strange... I just installed this container a couple months back and did an update today. Installed version was still `2.0.11`.
Are you certain you didn't already switch the repository to the mosquitto one?
Could you run `grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*` to verify?

Here's mine (after testing the PR):
```
/etc/apt/sources.list:deb http://deb.debian.org/debian bookworm main contrib
/etc/apt/sources.list:
/etc/apt/sources.list:deb http://deb.debian.org/debian bookworm-updates main contrib
/etc/apt/sources.list:
/etc/apt/sources.list:deb http://security.debian.org bookworm-security main contrib
/etc/apt/sources.list:
/etc/apt/sources.list.d/mosquitto.list:deb [arch=amd64 signed-by=/usr/share/keyrings/mosquitto-repo.gpg.key] http://repo.mosquitto.org/debian bookworm main

**Comment by dsiebel** [comment]
I just install up a fresh mqtt LXC from source. It installed `2.0.11`:

image

**Comment by dsiebel** [comment]
I think I might have found the issue:
The mosquitto repository was removed in March:
https://github.com/community-scripts/ProxmoxVE/commit/b58ae2b8924b554a9d4fcd404f3dede9c6ed3ba8

**Comment by MickLesk** [comment]
ah, strange. 

```bash
root@mqtt:~# grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
/etc/apt/sources.list:deb http://deb.debian.org/debian bookworm main contrib
/etc/apt/sources.list:
/etc/apt/sources.list:deb http://deb.debian.org/debian bookworm-updates main contrib
/etc/apt/sources.list:
/etc/apt/sources.list:deb http://security.debian.org bookworm-security main contrib
/etc/apt/sources.list:
/etc/apt/sources.list.d/mosquitto-bookworm.list:deb https://repo.mosquitto.org/debian bookworm main
```

I don't know why he did that. At least it runs very stable for me with approx. 50 devices + Zigbee2MQTT.

**Comment by dsiebel** [comment]
> I don't know why he did that. At least it runs very stable for me with approx. 50 devices + Zigbee2MQTT.

My guess is it had something to do with the way the GPG was handled.
The way it was implemented it would throw deprecation warnings and even caused issues at some point: https://github.com/tteck/Proxmox/issues/2617

From the commit history it looks like he was struggling to implement the gpg key handling, ultimately removing it altogether:

image

**Review by MickLesk — APPROVED** [review]
(text above...), then its fine for me.

**Pull request merged**
