### PR TITLE
Update ALL CT's to new default (Part 2)

### PR DESCRIPTION
**Pull request by MickLesk**
## Description
In association with PR: https://github.com/community-scripts/ProxmoxVE/pull/643

The following changes have been made:
- Introduction of the new header
- Scripts all standardized
- Standardized “Completed” script completion
- Introduction of TAGs in every CT
- Merging of license and LICENSE.md into one line
- Merge author and co-author into one line
- Standardized default values area with privileged differentiation
- An origin source (URL) is added to each script
- Alpine Updated to 3.20
- All indentations brought to a consistent level (Visual Studio Code)

**A template and a Contributor.md will follow in Part 3! You are all asked to contribute. I will provide the first draft. Feel free to give feedback then**

## Type of change
Please check the relevant option(s):

- [x] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #643

### CODE REVIEW

**Comment by havardthom** [comment]
I'm not really a fan of these "massive" PR updates with multiple different changes that are dependent on each other and that have to merged at the same time to work. It really is a huge risk and if something breaks it will be impossible to find the cause and we have to roll everything back. This could have been solved by having separate PRs for each proposed change and merging them one by one instead. For example all the changes related to the default settings change could have been one PR. Indentation fix could be one PR. Header info change could be one PR. Adding tags could be one PR. Wording and motd changes could be one PR etc. 

These PRs feels like an all or nothing ultimatum when it should not have to be. In my professional life I would not accept huge PRs with multiple unrelated changes to production like this. But it is done now, **I know you have put in huge amount of work and it is very good work!** but the way we are planning to push all these changes to production feels wrong to me. Luckily it's just an open source project and no one is gonna loose their job if something goes wrong, so I guess it's fine 😅 Just some thoughts for future PRs.

I'll probably have a look at this some time during the weekend or start of next week

**Comment by MickLesk** [comment]
Yes, I agree, I also left out all the "-install" scripts, otherwise it would simply be too much. That will be an seperate PR later, january or later :smile:

And because the changes are already a lot, I made the dev branch 😅
I have built about 40 of 195 CTs on my Dev Intel Nuc today, all without any problems. I think I'll manage another 30-40 tomorrow, Sunday is computer-free day and Monday the rest. If I notice anything else, I can fix it at my leisure.

**Comment by michelroegl-brunner** [comment]
> I have built about 40 of 195 CTs on my Dev Intel Nuc today, all without any problems. I think I'll manage another 30-40 tomorrow, Sunday is computer-free day and Monday the rest. If I notice anything else, I can fix it at my leisure.

If you ever need help testing, i can always assit with the 5 node HPE Server cluster i have free access to. 😅

**Comment by MickLesk** [comment]
Feel free to test random or the Website from above to bottom :D

**Comment by michelroegl-brunner** [comment]
Will do!

**Comment by michelroegl-brunner** [comment]
@MickLesk, i´m currently testing the scripts bottom to top but i have a wired bug/glitch with the whiptail/gui:

gui

I´m on the development branch atm.

**Comment by MickLesk** [comment]
> @MickLesk, i´m currently testing the scripts bottom to top but i have a wired bug/glitch with the whiptail/gui:
> 
> gui
> 
> I´m on the development branch atm. The script runs without a problem though.


yep ive pushed 2-3 changes, github need sometimes up 5min to refresh the script ^^

**Comment by michelroegl-brunner** [comment]
Yes, it´s working again. I also love the option to install default in verbose mode. (The verbose mode dose not work for me at the moment, just as fyi)

**Comment by MickLesk** [comment]
Now it works with verbose ;-)

**Comment by michelroegl-brunner** [comment]
Error
 Not for me :D

**Comment by MickLesk** [comment]
refresh your dns cache at node or logout / login ^^

**Comment by michelroegl-brunner** [comment]
I did, it is working now. I guess my caching was kinda wired. But verboes is working now, thank you for that feature ^^

**Comment by michelroegl-brunner** [comment]
whisparr.sh - Default Settings, none Verbose:

whisparr

**Comment by MickLesk** [comment]
> whisparr.sh - Default Settings, none Verbose:
> 
> whisparr


Random, too many requests against Github

**Comment by burgerga** [comment]
Thanks, that must have been a lot of work :O
Considering 
> * All indentations brought to a consistent level (Visual Studio Code)
You could include an https://editorconfig.org/ file to help contributors apply the settings across editors :)

**Comment by MickLesk** [comment]
> Thanks, that must have been a lot of work :O Considering
> 
> > * All indentations brought to a consistent level (Visual Studio Code)
> 
> You could include an https://editorconfig.org/ file to help contributors apply the settings across editors :)


I have no idea about that ^^

**Review by bramsuurdje — DISMISSED** [review]

**Review by michelroegl-brunner — DISMISSED** [review]

**Pull request merged**
