### PR TITLE
New Script: LubeLogger

### PR DESCRIPTION
**Pull request by quantumryuu**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Created install scripts for [Lubelogger](https://lubelogger.com/)

Fixes # (issue)
#48 
[Project board](https://github.com/orgs/community-scripts/projects/9/views/1?filterQuery=lube&pane=issue&itemId=87952039)

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
**jq** is needed to add some keys in the appsettings.json of lubelogger else it only work at http://localhost:5000

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Review by MickLesk — APPROVED** [review]
I have made a few mini adjustments. But so far it looks good.

2 themes however:
1. are the resources really sufficient? 500 MB is not really much.

2. are there default access data? I have only tested briefly, not yet extensively.

**Comment by kristocopani** [comment]
Hello @MickLesk, about the resources, it's quite lightweight. Did some tests yesterday before the PR and seemed fine.
What do you mean by default access data? Like an user? If yes, then there is no user/login form

**Comment by MickLesk** [comment]
> Hello @MickLesk, about the resources, it's quite lightweight. Did some tests yesterday before the PR and seemed fine.
> What do you mean by default access data? Like an user? If yes, then there is no user/login form

Allright. See it after my live Test Later ^^

**Comment by Banjer** [comment]
Thanks for adding this, much appreciated!

**Pull request merged**
