### PR TITLE
Tududi install script

### PR DESCRIPTION
**Pull request by beardcodes**
> **🛠️ Note:**  
> We are meticulous about merging code into the main branch, so please understand that pull requests not meeting the project's standards may be rejected. It's never personal!  
> 🎮 **Note for game-related scripts:** These have a lower likelihood of being merged.

---

## ✍️ Description
Provide a summary of the changes made and/or reference the issue being addressed.

 

- - -
**_Please remove unneeded lines!_**
- Related Issue: # (issue number, if applicable)  
- Related PR: # (if applicable)  
- Related Discussion: []()(if applicable)  

---

## 🛠️ Type of Change
Please check the relevant options:  
- [ ] Bug fix (non-breaking change that resolves an issue)  
- [ ] New feature (non-breaking change that adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to change unexpectedly)  
- [x] New script (a fully functional and thoroughly tested script or set of scripts)  

---

## ✅ Prerequisites
The following steps must be completed for the pull request to be considered:  
- [x] Self-review performed (I have reviewed my code to ensure it follows established patterns and conventions.)  
- [x] Testing performed (I have thoroughly tested my changes and verified expected functionality.)  
- [ ] Documentation updated (I have updated any relevant documentation)

---

## 📋 Additional Information (optional)
Provide any extra context or screenshots about the feature or fix here.

### CODE REVIEW

**Comment by michelroegl-brunner** [comment]
Please fill out the PR form and reopen it. else we can not review it. Thank you

**Comment by beardcodes** [comment]
I have filled and edited the form as requested Sir.

**Comment by MickLesk** [comment]
Various errors:
- No change to the build.func allowed
- No change to install.func allowed
- Missing -install.sh 
- massive error in the .sh

Does not adhere to any conventions of the desired PR quality.
Rejected.

**Comment by beardcodes** [comment]
sorry sir I saw in the guidelines to change the path in build.func and install.func to my forked repo.
I will look at the points mentioned and submit again sir.

**Comment by michelroegl-brunner** [comment]
@beardcodes Yes, but only during development for testing.

**Comment by beardcodes** [comment]
ok let me then fork another repo and resubmit my pr again

**Pull request closed without merging**
