### PR TITLE
Update microcode.sh

### PR DESCRIPTION
**Pull request by simonmcnair**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Updating the microcode doesn't depend on proxmox at all.  I, for example, run the proxmox kernel without installing proxmox-ve

Fixes # (issue)

## Type of change
Please check the relevant option(s):

- [ x] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [ yes] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ yes] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ yes] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
this can be tested on any machine by simply running it.  The diff highlights how small the change is.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Comment by remz1337** [comment]
Makes sense. How should I go if I want to test this, like what is your use case? A simple Debian machine (without Proxmox) then run this script to install the microcode?

Also, @simonmcnair please update the PR to follow the template:
- Description should be in the description section, not at the top
- Check boxes should be checked with X, not yes

**Comment by MickLesk** [comment]
Any News ? @simonmcnair

**Comment by newzealandpaul** [comment]
I am unsure what the point of removing the check is. @simonmcnair can you explain why you need to run this script on non-proxmox installs? 

In general I think all our scripts should only run on Proxmox.

**Comment by simonmcnair** [comment]
I thought I replied to this.

**Comment by simonmcnair** [comment]
> I am unsure what the point of removing the check is. @simonmcnair can you explain why you need to run this script on non-proxmox installs?
> 
> In general I think all our scripts should only run on Proxmox.

If something doesn't depend on proxmox why would you make it a dependency ?  that's crazy talk.  I gave you a valid use case.

**Comment by simonmcnair** [comment]
this can be tested on any machine by simply running it. The diff highlights how small the change is.

**Comment by simonmcnair** [comment]
I cannot believe you closed this with only 3 days of no reply, and didn't even sense check it.  If this is the way the new repo is going to be run, it's shocking.

**Comment by simonmcnair** [comment]
> I am unsure what the point of removing the check is. @simonmcnair can you explain why you need to run this script on non-proxmox installs?
> 
> In general I think all our scripts should only run on Proxmox.

" I, for example, run the proxmox kernel without installing proxmox-ve"

**Comment by havardthom** [comment]
image

We support ProxmoxVE, create a fork if you want to run on something else.

**Comment by simonmcnair** [comment]
What a ludicrous statement.  Yeah, lets make a dependency on something that it isn't dependant on.  Microcode has jack squat to do with Microcode.  Well.  You'll not be getting any more pull requests or donations from me.  I'm done with this repo.

**Comment by havardthom** [comment]
Sorry you feel that way, good luck with your future endeavors.

**Pull request closed without merging**
