### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by remz1337**
## Description

Fix some links still pointing to old repo

## Type of change
- [X] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)

### CODE REVIEW

**Comment by ianalexis** [comment]
tteck/Proxmox to community-scripts/ProxmoxVE
Looks good to me.

**Comment by MickLesk** [comment]
Fine. 

Merge? Or @havardthom will you check to?

**Comment by ianalexis** [comment]
@remz1337 maybe you want to edit the same thing at windows11-vm.sh
line 583.

**Review by havardthom — APPROVED** [review]

**Comment by remz1337** [comment]
> @remz1337 maybe you want to edit the same thing at windows11-vm.sh line 583.

windows11-vm.sh is only in my fork, but if it ever gets merged yes I'll make sure the links are updated

**Pull request merged**
