### PR TITLE
Add Release Drafter workflow

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Putting this PR up for discussion based on https://github.com/community-scripts/ProxmoxVE/discussions/23

Adds [Release Drafter workflow](https://github.com/release-drafter/release-drafter) which creates draft releases based on PRs merged to `main` branch. We can choose when to publish a new release. 

Benefits:
- Removes the need for a fully manual changelog
- Adds semantic versioning to our releases
- More explicit when/what changes
- Follows github release practices

Security aspects:
- Requires trust in [Release Drafter workflow](https://github.com/release-drafter/release-drafter), since [write permission](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents) is required to create a github release

Prerequisites:
- Add main branch protection so all commits to `main` requires PR (should have this regardless of this PR imo)
- Add new labels `breaking change`, `new script`, `update script`, `bug fix`, `chore` for labelling PR's
- An initial release (e.g. v1.0.0) should be published before using this

Also possible to use autolabeler which automatically labels PRs, but that means running the action on every PR. I disabled it because we have [2000 github action minutes](https://docs.github.com/en/get-started/learning-about-github/githubs-plans#github-free-for-organizations) per month. This should be enough for 2000 / 5min = 400 runs per month.

PRs

draft-release

## Type of change

Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by MickLesk** [comment]
Looks great! I will take a look tomorrow about this Pull.

**Comment by havardthom** [comment]
Regarding security aspect i also want to look into removing external dependency to Release Drafter and creating workflow from scratch

**Comment by newzealandpaul** [comment]
Looks good. I second replacing an external dependancy for security reasons.

**Comment by havardthom** [comment]
CLosing this and opening new PR without `Release Drafter` when it is ready

**Pull request closed without merging**
