### PR TITLE
Update Home Assistant core to python 3.13

### LINKED ISSUE #693: Home Assistant 2024.12
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

As of Home Assistant 2024.12, it requires Python 3.13 to be installed. The current Home Assistant Core install script only installs Python 3.12 which is the default for Ubuntu 24.04.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 24.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

_No response_

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Update the script to install Python 3.13 instead of 3.12. This is required by Home Assistant 2024.12. 
Python 13.3 is not yet in the official apt sources for Ubunut 24.02, so it uses  deadsnakes channel.

Home Assistant still installs with the current script version and seems to be working with python 3.12

Fixes #693 

## Type of change
Please check the relevant option(s):

- [X] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [X] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [X] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Comment by MickLesk** [comment]
Same Issue with homeassistant.sh ?

**Comment by MickLesk** [comment]
New one please, better for Changelog :-)

**Comment by towerhand** [comment]
Wouldn't it build from source better match the existing conventions in other scripts instead of adding the deadsnakes channel as an external source?

**Comment by michelroegl-brunner** [comment]
I could, but deadsnake is somewhat reputable in that regard and trusted by a wide comunity. 
Also it would make this long running script even longer.

But if requested by the majority, i will rewrite it :)

**Comment by havardthom** [comment]
On the fence about this one, Home Assistant Core 2024.12 was released 21 hours ago, let's not make any hasty decisions. Looks like Ubuntu 24.10 has python 3.13, so that might be an option soon

**Comment by michelroegl-brunner** [comment]
Yes. Python 3.13 was released sometime in oktober. 
I can do it either way or we postpone the python part until it is in Ubunut. In that case i would suggest we pin the Home Assistant Releas to 2024.11 for installs

**Comment by towerhand** [comment]
Right now, it's just a deprecated notice in HA. Luckily, we shouldn't have to worry about it for another month or two. As far as I know, nothing is broken that needs to be fixed urgently.

**Comment by newzealandpaul** [comment]
This commit should't be reopened as is. It for example says "Installing UV" after uv has been installed.

**Comment by michelroegl-brunner** [comment]
@newzealandpaul This PR will not get repoend. We should do a rework with python 3.13 when the time comes.

**Pull request closed without merging**
