### PR TITLE
Replace dash "-" with "/" in metadata

### PR DESCRIPTION
**Pull request by newzealandpaul**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Categories currently use the dash "-" symbol to represent shorthand "and" in category names in the metadata.

This is contra to normal English language usage and informal web usage where "-" is usually used to denote a category, or sub-category.

In informal english language "/" usually means logical "or" (a set encompassing all of A, all of B including all of A and B).

I also think it looks better. 

Matter/Zigbee/Zwave was renamed to continue to make sense. 

I have some further taxonomical changes I want to suggest but this needs to be first to avoid conflicting PR.

Screenshot:

Screenshot 2024-11-20 at 11 53 20 AM

You can have a look at a demo of it here (Edit: I use my main branch for testing so might not always be the demo):

https://newzealandpaul.github.io/ProxmoxVE/scripts

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)

I also tried "&" symbol and it didn't look as nice.

Screenshot 2024-11-20 at 11 39 14 AM

### CODE REVIEW

**Review by MickLesk — DISMISSED** [review]

**Comment by BramSuurdje** [comment]
i actually really like the "&" symbol, can we get some more opinions on this? i do agree that it at least needs to be change from "-"

**Comment by newzealandpaul** [comment]
> i actually really like the "&" symbol, can we get some more opinions on this? i do agree that it at least needs to be change from "-"

If the & symbol was used, which was my first try, then "Matter / Zigbee / ZWave" can stay the same other than including spaces.

**Comment by BramSuurdje** [comment]
Yeah, that seems like the best option in my opinion. I prefer using ‘&’ because it reads better, its like saying ‘Pi-hole and DNS’ instead of ‘Pi-hole … DNS’ but i.g its all personal preference 

so keep Matter / Zigbee / ZWave the same and change the others to &?

thats my proposal

**Review by havardthom — DISMISSED** [review]
Both works for me

**Comment by newzealandpaul** [comment]
Ok folks, & it is :) This change just needs reapproval please @havardthom @MickLesk . Can be viewed here:

https://newzealandpaul.github.io/ProxmoxVE/scripts

I went with "Matter, Zigbee & ZWave" as I just think this makes more sense and reads like how someone would describe the category "Matter, Zigbee and ZWave". For another discussion but I personally would rename this "Home Automation" but thats a discussion for another day.

**Review by MickLesk — APPROVED** [review]
Fine for me

**Review by havardthom — APPROVED** [review]

**Pull request merged**
