### PR TITLE
chore!: Upgrade jellyfin default to ubuntu 24.04

### PR DESCRIPTION
**Pull request by cospeedster**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Provide a summary of the changes made and/or reference the issue being addressed.

Related to tteck/Proxmox#2523 and further #473

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Comment by MickLesk** [comment]
Is this tested? 

Does HardwareAcc. running? With new LXC to? 
I dont use jellyfin

**Comment by cospeedster** [comment]
Result of first test install on a virtualized pve:

```
       __     ____      _____     
      / /__  / / /_  __/ __(_)___ 
 __  / / _ \/ / / / / / /_/ / __ \
/ /_/ /  __/ / / /_/ / __/ / / / /
\____/\___/_/_/\__, /_/ /_/_/ /_/ 
              /____/              
 
Using Default Settings
Using Distribution: ubuntu
Using ubuntu Version: 24.04
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 100
Using Hostname: jellyfin
Using Disk Size: 8GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Jellyfin LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ Downloaded LXC Template
 ✓ LXC Container 100 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: <redacted>
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.121.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set Up Hardware Acceleration
 ✓ Installed Jellyfin
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Jellyfin should be reachable by going to the following URL.
             http://<redacted>:8096

root@pve-test:~/ProxmoxVE# lxc-attach 100
root@jellyfin:/# cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by havardthom** [comment]
Perhaps this should temporarily be added as a separate script so it can be tested thoroughly before we remove the old stable/working script.

**Comment by cospeedster** [comment]
I'm not making good progress with testing, as there are hardcoded links to the github repository everywhere. This makes local development and testing very difficult. There is a lack of guidance on how to develop and test locally. We should work on that.

I don't think that updates should be kept as separate scripts. As a community, we should be able to test changes and then merge them.

**Comment by newzealandpaul** [comment]
> Perhaps this should temporarily be added as a separate script so it can be tested thoroughly before we remove the old stable/working script. Then we can start a discusssion on the new script and people can report back if there any problems. If no problems we can remove the old and replace with the new

Yes it should. I think JF is one of our highest profile scripts and one of the most used. It also requires encoding hardware to be accessed on the host, making it more complicated to setup.

Ubuntu 22.04.5 LTS is supported until 2027, so there is no rush unless JF starts to require newer libraries which is a possibility.

**Comment by cospeedster** [comment]
I understand the concerns. But I don't understand why we can't test it from this branch and merge it when it's been tested sufficiently.

Alternatively, I would suggest to implement the gid workaround for the case if Ubuntu 24.04 is selected during install.

**Comment by AT-StephenDetomasi** [comment]
Sorry if this sounds dumb, but is there any reason why I could not just use 22.04 for now, and simply run some commands to upgrade to 24.04 later?

**Pull request closed without merging**
