### PR TITLE
Add Template for Community-Scripts ORG

### PR DESCRIPTION
**Pull request by MickLesk**
## Description

**Description:**
This pull request provides template scripts designed as a starting point for community members who wish to create installation and update scripts for ProjectName on Debian-based systems. These templates are not intended for direct deployment but serve as customizable foundations for various configurations and environments.

**Key Features:**
Installation Script Template:

Includes placeholders and examples for setting up core dependencies, environment variables, and database configurations.
Demonstrates how to configure PostgreSQL and MariaDB databases, with sections for adding custom dependencies.
Provides an example of fetching the latest ProjectName release from GitHub, handling basic .env configuration, and logging generated credentials.
Annotated sections guide users on customizing installation steps for other required software or specific use cases.
Update Script Template:

Provides a template for checking the current ProjectName version against the latest GitHub release and outlines steps to stop, update, and restart services.
Includes clean-up instructions and prompts to handle limited storage and other update considerations.
Sample messages show users how to add feedback for logging, useful for adapting the template to various projects or requirements.

**Notes for Contributors:**
These scripts are templates only and require modification before use. Users should adjust database configurations, service names, and environment variables according to their specific project setup.
For any direct project use, please test the customized script on a development server to ensure compatibility and functionality.

### CODE REVIEW

**Review by Mellowlynx — DISMISSED** [review]

**Comment by remz1337** [comment]
After doing the review, I'm not sure having a template script is a good idea. There are too many different use cases that not one is really applicable for all. I would be inclined to do something like [vcpkg](https://github.com/microsoft/vcpkg?tab=readme-ov-file), where they describe the steps (like step 1: Fork the repo, step 2: create your branch MyProject, step 3: create install/myproject-install.sh and ct/myproject.sh, step 4: Open PR on github) and point the users to existing scripts that are good examples.

We could carefully select a few examples of varying complexity, like:

- Gitea (simple download and extract)
- Frigate (complex, multiple steps build with device passthrough, Python, Nginx and go2rtc)
- Vaultwarden (complex, with database setup)

**Comment by Mellowlynx** [comment]
I think as long it is made clear that it's just a template and that different use cases will require other options, it should fine.
But most people don't read, and every script can be used as a template.
So it this point, I'm not sure that the best step would be.

**Comment by MickLesk** [comment]
That's true, but we would have to harmonize all the scripts together. At the moment, many of them are massively different. In terms of sequences, standard conventions, command queries, etc.

Therefore, first of all a basic template for the correct sequence.

**Comment by havardthom** [comment]
I kind of agree with @remz1337 here, it's a good thought but I think having a template like this will probably cause more confusion and people will submit PR's with database setup and node.js repo when it's not really needed, because they just follow the template. Letting contributors explore the existing scripts to find the conventions is the best way for them to learn how things should be done imo. 
I think the **main** conventions are clear in existing scripts, but I agree that there are also differences, mainly in `update_script` functions in `ct`-scripts and in the `msg_info "Installing Application name"` sections of `install`-scripts. But maybe we should rather fix the scripts that are not following the norm instead.
If we do want a template, i think we should remove everything that is optional and only have the required parts, then direct people to existing scripts to see how the optional parts should be implemented.

**Comment by havardthom** [comment]
Here is a suggestion for a more barebone template that only contains required parts and some directions.

```
template.sh
#!/usr/bin/env bash
source <(curl -s https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/misc/build.func)
# Copyright (c) 2021-2024 tteck
# Author: community-scripts ORG
# CO-Author: EnterYourUsernameHere
# License: MIT
# https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE

function header_info {
clear
cat <<"EOF"
  ______                     __      __     
 /_  __/__  ____ ___  ____  / /___ _/ /____ 
  / / / _ \/ __ `__ \/ __ \/ / __ `/ __/ _ \
 / / /  __/ / / / / / /_/ / / /_/ / /_/  __/
/_/  \___/_/ /_/ /_/ .___/_/\__,_/\__/\___/ 
                  /_/                       
EOF
# Ascii header must be generated with Slant font: https://www.patorjk.com/software/taag/#p=display&f=Slant&t=Template
}
header_info
echo -e "Loading..."
APP="Template"
var_disk="2"
var_cpu="1"
var_ram="512"
var_os="debian"
var_version="12"
variables
color
catch_errors

function default_settings() {
  CT_TYPE="1"
  PW=""
  CT_ID=$NEXTID
  HN=$NSAPP
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET="dhcp"
  GATE=""
  APT_CACHER=""
  APT_CACHER_IP=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="no"
  VERB="no"
  echo_default
}

function update_script() {
header_info
if [[ ! -d /opt/template ]]; then msg_error "No ${APP} Installation Found!"; exit; fi
# Depending on the installation method chosen in `template-install.sh`, the update method may vary
# See other scripts for established conventions on preferred update methods
msg_info "Updating $APP LXC"
apt-get update &>/dev/null
apt-get -y upgrade &>/dev/null
msg_ok "Updated $APP LXC"
exit
}

start
build_container
description

msg_ok "Completed Successfully!\n"
echo -e "${APP} Setup should be reachable by going to the following URL.
         ${BL}http://${IP}:12345${CL} \n"

```

```
template-install.sh
#!/usr/bin/env bash

# Copyright (c) 2021-2024 tteck
# Author: community-scripts ORG
# CO-Author: EnterYourUsernameHere
# License: MIT
# https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE

source /dev/stdin <<< "$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt-get install -y curl
$STD apt-get install -y sudo
$STD apt-get install -y mc
# Add bare minimum(!) dependencies needed
msg_ok "Installed Dependencies"

# Add bare minimum(!) extra steps before installation, such as setting up repositories or database
# See other scripts for established conventions

msg_info "Installing Template"
# Preferred installation methods
# 1. Install from distribution package
# 2. Install from source
# 3. Use precompiled binary

# We dont want
# - Install with Docker
# - Install from other installation script

# See other scripts for established conventions on preferred install methods
msg_ok "Installed Template"

# Add bare minimum(!) extra steps after installation, such as setting up services
# See other scripts for established conventions

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get -y autoremove
$STD apt-get -y autoclean
msg_ok "Cleaned"
```

**Pull request closed without merging**
