### PR TITLE
PostgreSQL: Change authentication method from peer to md5 for UNIX sockets

### LINKED ISSUE #343: PostgreSQL LXC - can't authenticate via Adminer
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The default configuration requires to create a linux user along with the postgresql. To avoid this I had to update the pg_hba.conf changing the following line
`local   all             all                                     peer`
to
`local   all             all                                     md5`

See https://gist.github.com/AtulKsol/4470d377b448e56468baef85af7fd614

My suggestion would be to either update the deployment script or put a note on the script.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

Deploy the container and try to access the db server via Adminer

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

This PR fixes the Issue #343. I makes the changes suggested by the user. 

Fixes #343 

## Type of change
Please check the relevant option(s):

- [X ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [X] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [X] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Comment by MickLesk** [comment]
Tested? Work Adminer?

**Comment by michelroegl-brunner** [comment]
Yes, i have tested it and its working as far as i can tell :)
You may test it yourself if you want (https://raw.githubusercontent.com/michelroegl-brunner/ProxmoxVE/refs/heads/dev/ct/postgresql.sh).

**Comment by MickLesk** [comment]
Can you write a little discussion guide for migrating old instances?

I mean, like my last zigbee2mqtt Guide.

With Adminer Installations and without (Guide to add Adminer manually)

**Review by MickLesk — APPROVED** [review]

**Comment by michelroegl-brunner** [comment]
> Can you write a little discussion guide for migrating old instances?
> 
> I mean, like my last zigbee2mqtt Guide.
> 
> With Adminer Installations and without (Guide to add Adminer manually)

Sure, can do. I will have a look at it tomorrow.

**Comment by michelroegl-brunner** [comment]
@MickLesk 
I´ve added a guid on how to install adminer afterwards, as well how to do the changes by yourself. [GUIDE](https://github.com/community-scripts/ProxmoxVE/discussions/697)

**Comment by MickLesk** [comment]
Fine for me, need 1 Approve by @havardthom to merge the fix

**Review by havardthom — APPROVED** [review]

**Pull request merged**
