### PR TITLE
Add release drafter github workflow

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Adds a github workflow that creates a release draft on push to `main` branch. This will
- Create release draft with notes categorized based on merged PRs labels
- Adds semantic versioning and github tags
- Allow users to see everything that has changed (since last release)
- Allow users to get notified via github (if they want) 
- We don't have to manually update `CHANGELOG.md`

The draft release can be published when we want

For the release to be as correct as possible, PRs must be labelled accordingly. The autolabeler workflow will handle most PRs, but we should also manually check that PRs are labelled correctly before merging. It is also possible to fix labels on already merged PRs and rerun the release draft workflow manually before a release.

The config `.github/release-draft-config.json` specifies categories, corresponding labels and version increment for the github release tag.

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

Screenshot 1:
draft-1

Screenshot 2:
draft-2

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related https://github.com/community-scripts/ProxmoxVE/discussions/23

### CODE REVIEW

**Comment by MickLesk** [comment]
LGTM, but, where can i test? have you a good repo to show it?

**Review by judeibe — APPROVED** [review]
Looks good to me and it seems to work as the this pr got label `maintenance`

**Comment by judeibe** [comment]
> LGTM, but, where can i test? have you a good repo to show it?
> 
> €: For example, I like to work with milestones, which I set for a month.
> 
> Perhaps we could also do monthly releases? Always on the last day of the month?
> 
> Or more frequently if you like, every 14 days or similar

I think this can be solved by using a release branch. The release branch can correspond to the milestones. Since all merges into main are available right away. The release branch merged into main will cause main to be tagged with the semver.

**Review by MickLesk — APPROVED** [review]

**Comment by havardthom** [comment]
> LGTM, but, where can i test? have you a good repo to show it?
> 
> €: For example, I like to work with milestones, which I set for a month.
> 
> Perhaps we could also do monthly releases? Always on the last day of the month?
> 
> Or more frequently if you like, every 14 days or similar

You need repo access to run the action and see/publish draft release, you can merge this branch to your fork if you want to test it. I deleted the testing PRs on my fork because i had to synchronize with ProxmoxVE repo before creating this PR.

I think we can publish release whenever we want to update our users on what has changed, but I agree we should be careful not to do it too often. I think `Changelog.md` was probably updated once a day on average.

**Comment by havardthom** [comment]
We also need to manually create an initial `v.1.0.0` release to start as a baseline

**Comment by MickLesk** [comment]
> We also need to manually create an initial `v.1.0.0` release to start as a baseline

Do you do this? Im no longer on the PC today.

**Comment by havardthom** [comment]
> > We also need to manually create an initial `v.1.0.0` release to start as a baseline
> 
> Do you do this? Im no longer on the PC today.

Yes I can do before I merge it. Happy to have a few more opinions on this from @community-scripts/contributor first, since it is a project governance change.

**Comment by judeibe** [comment]
> It might be an unpopular opinion, but I do think we should not release like this. It's not software, so don't treat if like such. Why not push a new script right away. If someone wants to keep in the release loop, use ChangeDetection or enable notifications, or just visit.
> 
> I'm more for a bot that can push an update discord channel, you can follow, or something.
> 
> O, and this should also way in: image

If this was ttecks wish, I say we explore alternatives.

**Comment by havardthom** [comment]
I just want to make it clear that this PR is not about switching over to release-based software, from a technical standpoint I am 100% for doing rolling-release and always merging everything to `main` straight to production. This is purely about how we should communicate changes to our users. 

Tteck updated `CHANGELOG.md` manually and at a granularity he saw fit, but I think this will be harder to do when there are many contributors/maintainers involved. Should contributors update changelog themselves, or should one person keep track of all the changes and decide when to update it? Which changes should be included? We also have the website to consider now. 

For me using github release as a _communication platform_ is better, since it is automated and totally transparent on everything that changed. If a user is interested in new scripts just check that category, or someone might be interested in new features to the website, check that category. The only difference I see vs the `CHANGELOG.md` is the granularity in communication and having a version tag instead of just a date.

**Comment by MickLesk** [comment]
I agree with Havard.
I also find it difficult to decide what belongs in the changelog and what doesn't. If I stick to the current one, theoretically only absolutely critical breaking changes and new scripts. Theoretically, however, much more belongs in there.

This would make the following possible:
1. proper description of PRs and commits
2. proper presentation of bugfixes, features, new scripts etc.

**Comment by havardthom** [comment]
We could also open a poll in discussion to see what the users think?

**Pull request closed without merging**
