### PR TITLE
New Script: Maintainerr

### PR DESCRIPTION
**Pull request by caroipdev**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Provide a summary of the changes made and/or reference the issue being addressed.

Fixes #97

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [ ] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Comment by benscobie** [comment]
Hi, I'm a contributor for Maintainerr. We can definitely make this script a lot simpler. Currently we only build for Docker but I see no reason why we can't build artifacts for platforms like linux-x64. I'll see if I can make some time to look at this.

With the script the way it is, there's a high chance it'll break in the future as we move things around.

**Comment by caroipdev** [comment]
> Currently we only build for Docker but I see no reason why we can't build artifacts for platforms like linux-x64. I'll see if I can make some time to look at this.

I was thinking in having a look at the Maintainerr repo to see if it would be possible to add the built files for linux-x64, building both app & server takes quite a lot of time & resources (more than 1GB RAM).

I've tried to keep this script and the generated folder the closest to [DockerFile](https://github.com/jorenn92/Maintainerr/blob/main/Dockerfile) as possible, hopefully that would reduce the amount of work needed if Maintainerr moves things around.

**Comment by benscobie** [comment]
> I've tried to keep this script and the generated folder the closest to [DockerFile](https://github.com/jorenn92/Maintainerr/blob/main/Dockerfile) as possible, hopefully that would reduce the amount of work needed if Maintainerr moves things around.

The Dockerfile will be getting quite a big change soon with this PR: https://github.com/jorenn92/Maintainerr/pull/1369

I'll look at adding this into there.

**Comment by MickLesk** [comment]
> Hi, I'm a contributor for Maintainerr. We can definitely make this script a lot simpler. Currently we only build for Docker but I see no reason why we can't build artifacts for platforms like linux-x64. I'll see if I can make some time to look at this.
> 
> With the script the way it is, there's a high chance it'll break in the future as we move things around.

Hello,

thanks for your feedback, the script has given me a bit of a headache in terms of maintenance.
I think a linux%64 solution is much better, it can be integrated properly and almost error-free.

**Comment by caroipdev** [comment]
> the script has given me a bit of a headache in terms of maintenance.

I still believe it will still be a headache because we still need to do the db migrations and move files around, it will simplify but not be "almost error-free" :D

**Comment by benscobie** [comment]
> I still believe it will still be a headache because we still need to do the db migrations and move files around, it will simplify but not be "almost error-free" :D

This hopefully won't be the case. It should look similiar to some of the other scripts; download and extract archive, data folder creation and some chmod. Database migrations are automatically run on startup.

**Comment by MickLesk** [comment]
I would probably close the PR until Maintainerr provides a linux file. Because then the script might only have 10-15 lines of main code. (like nextpvr or other deb / linux installations)

**Comment by caroipdev** [comment]
> I would probably close the PR until Maintainerr provides a linux file. Because then the script might only have 10-15 lines of main code. (like nextpvr or other deb / linux installations)

Up to you, I personally would prefer having something working until the Maintainerr devs have time to work on  that and then update the script, instead of not having anything and then having the script created "from scratch" when Maintainerr provides the built files. 

Just commited my latest changes, locally it seems to be working, just pushed for future reference :)

**Comment by danielcherubini** [comment]
So, looks like that PR was merged.. @caroipdev is there any chance of opening a new one?

**Comment by benscobie** [comment]
You need this PR first: https://github.com/jorenn92/Maintainerr/pull/1562

**Pull request closed without merging**
