### PR TITLE
Outdated: Add JSON Documents for Each Script

### PR DESCRIPTION
**Pull request by newzealandpaul**
# Acknowledgments 

I want to acknowledge @tteck who put this all together in the first pace, this just builds upon their work.

I also want to acknowledge the amazing work @BramSuurdje put the database together on the database and suggested the json schema. Having this in the first place made this job a lot easier.

Also @havardthom who consulted during this process and helped move things along.

## Description

This merge adds a json/ directory with a .json file for each script. 

The json structure is in the format proposed by @havardthom with some minor changes due to discovery of information as I wrangled the data.

The data is extracted from the pocketbase DB in consultation with @BramSuurdje. It also parses the scripts (ct, vm and misc) for details.

The json format is as follows:

```json
{
    "name": "Emby Media Server", # The human formatted name/title
    "slug": "emby", # The slug, which is the script name without the file ext.
    "categories": [
        "Media - Photo" # The categories
    ],
    "date_created": "2024-05-02", # When the script was first added
    "type": "ct", # This differs slightly from the db. The type is ct, vm or misc. The frontend can render ct as LCX etc.
    "updateable": 0, # 0 or 1
    "privileged": 0, # 0 or 1
    "interface_port": "8096", 
    "documentation": "",
    "website": "https://emby.media/",
    "logo": "https://github.com/home-assistant/brands/blob/master/core_integrations/emby/icon.png?raw=true", 
    "description": "Emby brings together your personal videos, music, photos, and live television.",
    "install_methods": [
        {
            "type": "default",
            "script": "ct/emby.sh", # this is the script path from the root of the repo. The frontend code can generate the installer command from this.
            "resources": {
                "cpu": "2",
                "ram": "2048", # This is the value extracted from the script itself, RAM is specified in MB
                "hdd": "8",  # Hdd is specified in GB
                "os": "ubuntu",
                "version": "22.04"
            }
        }
    ],
    "default_credentials": {
        "username": "",
        "password": ""
    },
    "alerts": [ # We can have multiple alerts.
        {
            "alert": "With Privileged/Unprivileged Hardware Acceleration Support" 
        }
    ]
}
```

## Notes

I found a couple of scripts that are in the database but no longer exist as scripts:

1. scrutiny
2. collabora-online

So I think keeping the database in the repo as static files that can be committed or changed in lock-step with the scripts is a good idea. In the future we can automate checking that new scripts have a correct json file.

The script that generated these json files can be found [here](https://gist.github.com/newzealandpaul/897f59fb04cec2dc90fad15084e5a7de).

This wrangling job took quite a long time dealing with edge cases etc.

A script, or even a jq one liner could generate a categories.json file.

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)
- [ ] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by havardthom** [comment]
@BramSuurdje created the json schema, not me 😊

**Comment by newzealandpaul** [comment]
> @BramSuurdje created the json schema, not me 😊

Well I appreciate the support anyway

**Comment by havardthom** [comment]
Looks great!

Some thoughts for this PR
- Should we use `null` instead of empty types for optional fields? Better to be explicit and will be easier to type in typescript imo.
- should `category` be a list? I would think a script has one category. List makes sense for something like `tags`
- `alerts` sounds serious, are they actually `notes` or `messages` or `additional_info`?
- any particular reason for having alert strings in objects instead of directly in list?

Some thoughts for future
- Eventually we could also fetch `interface_port` and `resources` from ct script, so we don't have to update them in two files.
- `updateable`, some scripts have support for application update, while some only update the LXC, should we separate and be explicit about this?
- Add a field for github source code?

**Comment by newzealandpaul** [comment]
> Looks great!

Thank you

> * Should we use `null` instead of empty types for optional fields? Better to be explicit and will be easier to type in typescript imo.

I had wondered about this. I am happy to switch them to null.

> * should `category` be a list? I would think a script has one category. List makes sense for something like `tags`

Someone had commented, I think in discussions, that some scripts should be in multiple categories. I think there will at least be one script at some point in time that needs to be in two categories. Taxonomy is hard!

> * `alerts` sounds serious, are they actually `notes` or `messages` or `additional_info`?

How about we call them notes, which has a type and a text

```
notes: [
{text: "An alert", type: "alert"},
{text: "A note", type: "note"},
{text: "A note", type: "update_info"}
]

Right now we should set them all to alerts as they are on the website now. Overtime we can move less serious alerts to be of type note. 

> Some thoughts for future
> 
> * Eventually we could instead fetch `interface_port` and `resources` from ct script, so we don't have to update them in two files.

Yes agreed. 

> * `updateable`, some scripts have support for application update, while some only update the LXC, should we separate and be explicit about this?

Yes I think that would be a good idea.

> * Add a field for github source code?

To the source code of the applications themselves?

Thanks for the feedback. I can resubmit a pull request as its quick for me to regenerate the json.

**Comment by newzealandpaul** [comment]
It’s probably worth mentioning that the schema does not need to be perfect, it’s not an external api so we can evolve it over time.

**Comment by judeibe** [comment]
It would be nice if `"updateable": 0, # 0 or 1`  was a bool. The site would not have to convert it then.

**Comment by newzealandpaul** [comment]
> It would be nice if `"updateable": 0, # 0 or 1` was a bool. The site would not have to convert it then.

That is also a simple fix. I wondered about that too. The only thing is I wonder if undateable is not binary. There might be more than 2 states depending on how upgradable it is.

**Comment by remz1337** [comment]
I started a discussion because I think it's more of a future improvements, but maybe we could do it now given we are building the JSON for all scripts.

https://github.com/community-scripts/ProxmoxVE/discussions/83

I'm essentially suggesting to add attributes for scripts that need more resources when installing/updating their app

**Pull request closed without merging**
