### PR TITLE
Show Changelog on Mobile Devices

### PR DESCRIPTION
**Pull request by MickLesk**

### CODE REVIEW

**Comment by havardthom** [comment]
@MickLesk did you test this, was it not hidden for a reason? On my phone the search bar is overflowing outside the screen now

**Comment by MickLesk** [comment]
On my not, but IT was clickble without Icon 🤔

**Comment by MickLesk** [comment]
Take a look here, the changelog was also a dark square before. I have left Discussions as it is for now. 

How does it look for you?

**Comment by havardthom** [comment]
Ah ok, generally we should support width down to `320px`. But since this fixed something else we can leave it for now, the landing page is generally not responsive atm, so can fix it later

image

**Comment by MickLesk** [comment]
& we need a category view :smile:

**Pull request merged**
