### PR TITLE
Added Support for SnipeIT App

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Provide a summary of the changes made and/or reference the issue being addressed.

Fixes # (issue)

## Type of change
Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [X] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [X] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [X] Testing performed (I have tested my changes, ensuring everything works as expected)
- [X] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

Added the script to pull the latest docker from the SnipeIT App.
And please be kind, this is my first ever contribution to a OpenSource Projekt :) 

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Review by MickLesk — CHANGES_REQUESTED** [review]
We dont support Docker-Scripts. Only Bare Metal Scripts without Docker. 😄 
For Docker, everyone can use the docker or dockge Script 👍🏻

**Comment by michelroegl-brunner** [comment]
> We dont support Docker-Scripts. Only Bare Metal Scripts without Docker. 😄 
> 
> For Docker, everyone can use the docker or dockge Script 👍🏻 

Oh, ok. I did not know that. In that case you might want to put the pull request on hold or close it until i got the bare metal install working. Bit i do not think this will be a major problem.
Btw. Do you guys have some sort of developer wiki or something alike? I dug around GitHub, but i was unable to find anything like that 😁

**Comment by MickLesk** [comment]
In the next weeks, currently i change many in the core 😄 
https://github.com/community-scripts/ProxmoxVE/discussions/486

**Comment by havardthom** [comment]
Closing, feel free to open a new PR with bare metal install

**Pull request closed without merging**
