### PR TITLE
Update Zabbix to 7.2. Release

### PR DESCRIPTION
**Pull request by MickLesk**
## ✍️ Description
Update to Zabbix 7.2
 

- - -
**_Please remove unneeded lines!_**
- Related Issue: #937 

---

## 🛠️ Type of Change
Please check the relevant options:  
- [x] Bug fix (non-breaking change that resolves an issue)  
- [x] New feature (non-breaking change that adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to change unexpectedly)  
- [ ] New script (a fully functional and thoroughly tested script or set of scripts)  

---

## ✅ Prerequisites
The following steps must be completed for the pull request to be considered:  
- [x] Self-review performed (I have reviewed my code to ensure it follows established patterns and conventions.)  
- [x] Testing performed (I have thoroughly tested my changes and verified expected functionality.)  
- [x] Documentation updated (I have updated any relevant documentation)

---

## 📋 Additional Information (optional)
Provide any extra context or screenshots about the feature or fix here.

### CODE REVIEW

**Review by michelroegl-brunner — APPROVED** [review]

**Comment by JohnyBeGood** [comment]
When I try to use "update" inside the LXC I get this:

` _____         __    __    _     
/__  /  ____ _/ /_  / /_  (_)  __
  / /  / __ `/ __ \/ __ \/ / |/_/
 / /__/ /_/ / /_/ / /_/ / />  <  
/____/\__,_/_.___/_.___/_/_/|_|  
                                 

  ✔️  Stopped Zabbix Services
 ⠸ Updating Zabbix LXC 
[ERROR] in line 47: exit code 0: while executing command wget -q https://repo.zabbix.com/zabbix/7.2/debian/pool/main/z/zabbix-release/zabbix-release_latest+debian12_all.deb

root@zabbix:~# 

It appears url is wrong?`

**Comment by MickLesk** [comment]
Try again

**Comment by JohnyBeGood** [comment]
Getting different error now:

` _____         __    __    _
/__  /  ____ _/ /_  / /_  (_)  __
  / /  / __ `/ __ \/ __ \/ / |/_/
 / /__/ /_/ / /_/ / /_/ / />  <
/____/\__,_/_.___/_.___/_/_/|_|


 ⠋Failed to stop zabbix-agent2.service: Unit zabbix-agent2.service not loaded.
 ⠇
[ERROR] in line 36: exit code 0: while executing command systemctl stop zabbix-server zabbix-agent2

root@zabbix:~#

`
Old tteck script did not use 'zabbix-agent2'. Now is I guess a requirement.

**Comment by michelroegl-brunner** [comment]
Try systemctl start zabbix-server zabbix-agent2 befor you update.

**Comment by JohnyBeGood** [comment]
```
root@zabbix:~# systemctl start zabbix-server zabbix-agent2
Failed to start zabbix-agent2.service: Unit zabbix-agent2.service not found.
root@zabbix:~#
```

**Comment by MickLesk** [comment]
> Getting different error now:
> 
> ` _____         __    __    _
> /__  /  ____ _/ /_  / /_  (_)  __
>   / /  / __ `/ __ \/ __ \/ / |/_/
>  / /__/ /_/ / /_/ / /_/ / />  <
> /____/\__,_/_.___/_.___/_/_/|_|
> 
> 
>  ⠋Failed to stop zabbix-agent2.service: Unit zabbix-agent2.service not loaded.
>  ⠇
> [ERROR] in line 36: exit code 0: while executing command systemctl stop zabbix-server zabbix-agent2
> 
> root@zabbix:~#
> 
> `
> Old tteck script did not use 'zabbix-agent2'. Now is I guess a requirement.


Agent2 is required since many weeks. Install manually. Its not a Script issue here

**Comment by JohnyBeGood** [comment]
Installed agent2 and am still unable to update. Fresh install would not have this issue. But this is an upgrade from old script.

```
 _____         __    __    _
/__  /  ____ _/ /_  / /_  (_)  __
  / /  / __ `/ __ \/ __ \/ / |/_/
 / /__/ /_/ / /_/ / /_/ / />  <
/____/\__,_/_.___/_.___/_/_/|_|


  ✔️  Stopped Zabbix Services
 ⠸ Updating Zabbix LXC
[ERROR] in line 50: exit code 0: while executing command apt-get install --only-upgrade zabbix-server-pgsql zabbix-frontend-php zabbix-agent2 zabbix-agent2-plugin-* &> /dev/null

root@zabbix:~#

```

**Comment by MickLesk** [comment]
You need to read the Changelog. 

Install all agent2 Files and remove agent. Or do an Clean Install. 

This is another issue here. Dont Spam it.

**Pull request merged**
