### PR TITLE
feat: allow adding SSH authorized key for root (advanced settings)

### PR DESCRIPTION
**Pull request by dsiebel**
## ✍️ Description

Adds and additional input to the advanced settings flow that allows adding an SSH authorized key for the root user.

- Related Discussion: #860 

---

## 🛠️ Type of Change
Please check the relevant options:  
- [ ] Bug fix (non-breaking change that resolves an issue)  
- [x] New feature (non-breaking change that adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to change unexpectedly)  
- [ ] New script (a fully functional and thoroughly tested script or set of scripts)  

---

## ✅ Prerequisites
The following steps must be completed for the pull request to be considered:  
- [x] Self-review performed (I have reviewed my code to ensure it follows established patterns and conventions.)  
- [ ] Testing performed (I have thoroughly tested my changes and verified expected functionality.)  
- [ ] Documentation updated (I have updated any relevant documentation)

---

## 📋 Additional Information (optional)
Provide any extra context or screenshots about the feature or fix here.  

I came up with multiple ways to implement this, but ultimately decided to go for the most pragmatic one to get a feel first.
Other possible implementation I had in mind:

- option to forward authorized_keys from the PVE host (multi select menu) to the newly created container / vm
- use a "well-known" file location or environment variable to contain the SSH key to authorize

### CODE REVIEW

**Comment by MickLesk** [comment]
Can you push this change into develop to test?

**Comment by dsiebel** [comment]
> Can you push this change into develop to test?

I don't think I can push to any branch. 😅 
Do you mean re-base the PR to merge to develop?

**Comment by michelroegl-brunner** [comment]
pull from develop branch, make your changes, push not to main but to develop.

**Comment by dsiebel** [comment]
@michelroegl-brunner @MickLesk 
There you go: https://github.com/community-scripts/ProxmoxVE/pull/1060

**Pull request closed without merging**
