### PR TITLE
Add a discussion template for script requests

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
I am meticulous when it comes to merging code into the main branch, so please understand that I may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Fixes https://github.com/community-scripts/ProxmoxVE/discussions/6

Add template for script requests in discussions. **New discussion category "Request script" must be added by a repo owner first (see third screenshot).**

Default form:

default_form

Opened discussion:

request_script_open

Create new discussion category:

request_script

## Type of change

Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [ ] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by tteck** [comment]
Didn't work as expected?

**Comment by MickLesk** [comment]
I don't see any modification here too, is there anything missing?

**Comment by havardthom** [comment]
You need to add the new discussion category manually, as I've shown in 3rd screenshot. There is a small edit icon on discussions page side menu

**Comment by MickLesk** [comment]
I just had the same thing. (Only a different icon). But it still didn't work. I can try it again.

**Comment by MickLesk** [comment]
Ah now it works. I think its case sensitive or i do an spell mistake

**Comment by tteck** [comment]
Nice!

**Comment by havardthom** [comment]
image

this extra checkbutton is not on my fork, hm

**Comment by havardthom** [comment]
Guess it's just for first discussion
image

**Pull request merged**
